export const defaultSurprises={
 story:{title:'Little Moments',text:'A collection of happy memories',label:'PLAY THE MEMORIES',imageId:''},
 letter:{title:'Your letter',text:'A message to brighten your day',label:'OPEN YOUR ENVELOPE',imageId:'',heading:'Dear {name},',eyebrow:'A LETTER, JUST FOR YOU'},
 gift:{title:'One more surprise',text:'A little birthday magic',label:'UNWRAP THIS ONE',imageId:'',heading:'May your wish come true!',eyebrow:'HAPPY BIRTHDAY, {name}',message:'Here’s to a year full of happiness, new adventures, and wonderful possibilities.',note:'Wishing you a truly wonderful birthday. ♡',signature:'With warm birthday wishes.',giftName:'',giftMessage:'',giftUrl:'',giftButton:'Open your gift'}
};
export function mergeContent(saved:any){return {...defaults,...saved,welcome:{...defaultWelcome,...saved.welcome},welcomeMedia:{...defaults.welcomeMedia,...saved.welcomeMedia},surprises:{story:{...defaultSurprises.story,...saved.surprises?.story},letter:{...defaultSurprises.letter,...saved.surprises?.letter},gift:{...defaultSurprises.gift,...saved.surprises?.gift}}};}
export const defaultWelcome={speech:'I made you something… ♡',eyebrow:'A SURPRISE WITH YOUR NAME ON IT',titleLine:'A little secret.',titleLead:'A lot of',titleAccent:'love.',prompt:'Are you ready for your birthday surprise?',yesLabel:'Yes, I’m ready!',noLabel:'No',noSpeech:'Wrong answer, birthday human!',noEyebrow:'TEDDY WOULD LIKE A WORD',noTitle:'How dare you choose “No”!',noMessage:'Go back and select “Yes”. Teddy insists. ♡',retryLabel:'Let me try again'};
export type ChapterEdit={title:string;place:string;caption:string;note:string};
export const defaults={name:'you',intro:'A little celebration, a few happy surprises, and a whole lot of birthday wishes.',letter:'Some people make ordinary days feel extraordinary. You are one of those people.\n\nHere’s to your laughter, your dreams, and all the memories we haven’t made yet. I hope this next chapter brings you as much happiness as you bring into my life.\n\nHappy birthday. I’m so glad our paths crossed.',signature:'With all my love',birthday:'',welcomeMedia:{mode:'classic',imageId:'',motion:'float'},surprises:defaultSurprises,welcome:defaultWelcome,chapterEdits:{} as Record<string,ChapterEdit>,memories:[] as {id:string;title:string;caption:string;date:string;chapter?:string}[]};
