'use client';
import {defaults} from './defaults';
import {chapters} from './story-data';
import AnimatedTeddy from './animated-teddy';
import WelcomeVisual from './welcome-visual';
export default function Gallery({data,onWelcome}:{data:typeof defaults;onWelcome:(imageId:string)=>void}){
const uploaded=new Map<string,{title:string;uses:string[]}>();
function add(id:string,title:string,use:string){if(!id)return;const existing=uploaded.get(id);if(existing){existing.uses.push(use);}else uploaded.set(id,{title,uses:[use]});}
data.memories.forEach(m=>add(m.id,m.title,chapters.find(c=>c.id===m.chapter)?.title||'Gallery picture'));
add(data.welcomeMedia.imageId,'Your welcome picture',data.welcomeMedia.mode==='upload'?'Welcome screen':'Saved welcome picture');
(['story','letter','gift'] as const).forEach(k=>add(data.surprises[k].imageId,data.surprises[k].title,k==='story'?'Little Moments selection card':k==='letter'?'Letter & selection card':'Gift & selection card'));
return <div className="gallery-admin"><div className="editor-card"><span className="eyebrow">PICTURES ALREADY ON YOUR PAGE</span><h2>Your little gallery.</h2><p className="hint">Your uploaded pictures and the artwork used on the site. Choose an uploaded picture for the welcome screen, then Save changes.</p></div><h3>Your uploaded pictures · {uploaded.size}</h3>{uploaded.size?<div className="admin-gallery-grid">{Array.from(uploaded).map(([id,p])=><article className="admin-gallery-card" key={id}><img src={'/api/photos/'+id} alt={p.title}/><div><h4>{p.title}</h4><p>{Array.from(new Set(p.uses)).join(' · ')}</p><button className="text-button" onClick={()=>onWelcome(id)}>Use on welcome screen</button></div></article>)}</div>:<p className="hint">No uploaded pictures yet. Add them in Welcome screen, Memory chapters, or Three surprises.</p>}<h3>Sample moment artwork</h3><div className="admin-gallery-grid">{chapters.filter(c=>c.art).map(c=><article className="admin-gallery-card" key={c.id}><img src={"/story/"+c.art+".png"} alt={c.title}/><div><h4>{c.title}</h4><p>Default artwork · replace in Memory chapters</p></div></article>)}</div><h3>Teddies & original artwork</h3><div className="admin-gallery-grid"><article className="admin-gallery-card"><div className="gallery-animation"><WelcomeVisual media={{mode:'pink',imageId:'',motion:'none'}}/></div><div><h4>Pink teddy with roses</h4><p>{data.welcomeMedia.mode==='pink'?'Current welcome animation':'Available in Welcome screen'}</p></div></article><article className="admin-gallery-card"><img src="/gallery/pink-teddy-original.png" alt="Classic teddy"/><div><h4>Classic teddy picture</h4><p>{data.welcomeMedia.mode==='original'?'Current welcome picture':'Available in Welcome screen'}</p></div></article>{(['wave','pout','celebrate'] as const).map((m,i)=><article key={m} className="admin-gallery-card"><div className="gallery-animation"><AnimatedTeddy mood={m}/></div><div><h4>{['Waving teddy','Playful teddy','Birthday dancing teddy'][i]}</h4><p>{['Letter teddy & optional welcome','Original welcome’s No response','Memory chapter & celebration'][i]}</p></div></article>)}</div></div>;
}
